function outputdata = Adapted_simPAF_ECG_generator_iterator(rrLength_array,APBrate_array, onlyRR_array, medEpis_array, stayInAF_array, AFburden_array, noiseType_array, noiseRMS_array, realRRon_array, realVAon_array, realAAon_array, repeats)

load('DATA_PQRST_real');
load('DATA_f_waves_real');
DATAnoises = load('DATA_noises_real');
load('DATA_RR_AF_real');
load('DATA_RR_SR_real');

outputdata = struct();
counter = 1;

for i =  1:repeats
    for rrLength = rrLength_array
        for APBrate = APBrate_array
            for onlyRR = onlyRR_array
                for AFburden = AFburden_array
                    for medEpis = medEpis_array
                        for stayInAF = stayInAF_array
                            for noiseType = noiseType_array
                                for noiseRMS =noiseRMS_array
                                    if noiseType == 0 & noiseRMS ~= 0
                                        continue
                                    end
                                    for realRRon = realRRon_array
                                        for realVAon = realVAon_array
                                            [simPAFdata, initialParameters] = Adapted_simPAF_ECG_generator(rrLength, realRRon, realVAon, realVAon, AFburden, stayInAF, APBrate, noiseType, noiseRMS, onlyRR, DATApqrst, DATAfWaves, DATAnoises, DATArrSR, DATArrAF);
                                            counterstr = append('s',num2str(i),'c',num2str(counter));
                                            outputdata.(counterstr) = struct( ...
                                                'rr', simPAFdata.rr, ...
                                                'multileadECG', simPAFdata.multileadECG, ...
                                                'multileadVA', simPAFdata.multileadVA, ...
                                                'multileadAA', simPAFdata.multileadAA, ...
                                                'multileadNoise', simPAFdata.multileadNoise, ...
                                                'QRSindex', simPAFdata.QRSindex, ...
                                                'targets_SR_AF', simPAFdata.targets_SR_AF, ...
                                                'targets_APB', simPAFdata.targets_APB, ...
                                                'pafBoundaries',simPAFdata.pafBoundaries, ...
                                                'pafEpisLength', simPAFdata.pafEpisLength, ...
                                                'ecgLength', simPAFdata.ecgLength, ...
                                                'ip_fibFreqz',initialParameters.fibFreqz, ...
                                                'ip_rrLength',initialParameters.rrLength, ...
                                                'ip_APBrate',initialParameters.APBrate, ...
                                                'ip_realRRon',initialParameters.realRRon, ...
                                                'ip_realVAon',initialParameters.realVAon, ...
                                                'ip_realAAon',initialParameters.realVAon, ...
                                                'ip_stayInAF',initialParameters.stayInAF, ...
                                                'ip_AFburden',initialParameters.AFburden, ...
                                                'ip_noiseType',initialParameters.noiseType, ...
                                                'ip_noiseRMS', initialParameters.noiseRMS, ...
                                                'ip_i', i);
                                            counter = counter + 1;
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

clear DATA_f_waves_real
clear DATApqrst
clear DATAnoises
clear DATArrSR
clear DATArrAF

end

